### ISSUE TITLE
[Invasion] doesn't load on bot start

### ISSUE THREAD

**Issue by Chovin** [Chovin/Dumb-Cogs#14]
this is the culprit. the cog tries to load during bot startup and the bot is only ready once all cogs have been loaded. we can't simply remove this though since we need the bot to be ready to get the guilds, so we need to load the invasion tasks as a separate task. https://github.com/Chovin/Dumb-Cogs/blob/3c2843772214cc9ec345a3203f051a74c6257084/invasion/invasion.py#L78-L79

**Comment by shahzdvp** [comment]
i would like to work on this

**Comment by Chovin** [comment]
sure thing! just let me know if you need any help
