### ISSUE TITLE
[HammerTime] errors out when a dm is sent to the bot

### ISSUE THREAD

**Issue by Chovin** [Chovin/Dumb-Cogs#22]
<img width="586" alt="image" src="https://github.com/user-attachments/assets/7864bbf6-c5cf-4454-8dff-b8bb864d5e22">
should be an easy fix, just make sure that guild exists and quit early if it doesn't

**Comment by shahzdvp** [comment]
i would like work on this

**Comment by Chovin** [comment]
Cool, Go for it! Let me know if you need any help
